version: "3"

services:
  mongo-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo-db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-db:27017/

  redis:
    image: redis
    command: redis-server
    ports:
      - 6379:6379

  web:
    build: .
    command: npm run dev
    container_name: uptime-api
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "7000:7000"
    depends_on:
      - mongo-db
      - redis
    env_file:
      - .env
    environment:
      - 'REDIS_HOST=redis'
      - 'REDIS_PORT=6379'
      - 'MONGO_HOST=mongo-db'
      - 'MONGO_USER=root'
      - 'MONGO_PASS=example'
      - 'MONGO_PORT=27017'
      - 'MONGO_DB_NAME=monitoring'
      - 'MAIL_USER=hwlbxov4jx6i2ud2@ethereal.email'
      - 'MAIL_PASS=EPD3MHAzf2PcHrcys2'
      - 'MAIL_HOST=smtp.ethereal.email'
      - 'MAIL_HOST_PORT=587'
      - 'MAIL_HOST_SECURE=false'
      - 'NODE_ENV=development'

